### ISSUE TITLE
Pas d'instruction pour installer eslint avec npm

### ISSUE THREAD

**Issue by Lifeismana** [romulusFR/lifap5-backend-2019-2020#10]
Sans instruction pour installer eslint, c'est un peu laborieux de trouver la bonne commande mais à force d'essayer, j'ai trouvé:
 `npm i -D eslint eslint-config-prettier eslint-plugin-prettier prettier eslint-plugin-promise eslint-plugin-import eslint-config-airbnb-base`
Sauf si le but est de forcer à chercher pour trouver la manière de l'installer, il est peut-être préférable de fournir des instructions, cette commande ou encore de fournir un package.json avec uniquement ces packages requis pour la config fourni.
Il peut être aussi intéressant de parler du fichier .gitignore, ou de le fournir pour éviter de polluer les répertoires git .
En fonction du choix, je peux en faire le pull-request !

**Comment by romulusFR** [comment]
Il y a un fichier [package.json](https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/package.json) de fourni, faire `npm install` installe tout, y compris les devDependencies où il y a eslint.
Le [.gitignore](https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/.gitignore) est aussi présent.

Donc au final, que faire : mettre une section installation avec `npm install` dans le README ?

**Comment by romulusFR** [comment]
Du coup, j'ai restructuré <https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/DEPLOYMENT.md#installation-pour-le-d%c3%a9veloppement> pour que ce soit plus clair. A voir donc ce qu'il manque

**Comment by Lifeismana** [comment]
Mais ni le package.json ni le .gitignore ne sont fournis avec le zip du client de départ, c'est ce que je trouve de surprenant.
Effectivement maintenant l'installation est plus clair. Si on veut faire une installation minimale, juste en utilisant le serveur lifap5, est-ce qu'on a vraiment besoin d'installer postgres ? Une dernière chose, c'est qu'il manque un petit lien vers cette page sur le sujet du projet ou bien un lien en plus de ceux à la racine du serveur lifap5

**Comment by romulusFR** [comment]
Je n'avais pas compris qu'il s'agissait d'une issue sur le client de départ. Effectivement, c'est une bonne idée de mettre un package.json.

Pour Postgres, on ne peut pas trop faire sans

**Comment by romulusFR** [comment]
Je réouvre du coup car on a pas bien conclu @Lifeismana une Pull Request ?

**Comment by Lifeismana** [comment]
Fait au cas où vous n'auriez pas vu
