### ISSUE TITLE
Rate limiter

### ISSUE THREAD

**Issue by MrBrownstone2000** [romulusFR/lifap5-backend-2019-2020#13]
Le rate limiter est un peu bas, il mériterait peut-être d'être changé à 12 requêtes par seconde.
Quand on teste son client, on peut vite avoir beaucoup de requêtes qui arrivent en même temps, nottamment quand on répond à beaucoup de quizzes différents

Dans tout les cas, il faudrait indiquer sa présence dans la documentation de l'API

(p1807560)

**Comment by romulusFR** [comment]
Ajouté dans la doc https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/SUJET.md#remarques-importantes. On met aussi une dans la nouvelle FAQ https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/FAQ.md

**Comment by romulusFR** [comment]
Par contre, on a déjà droit à des rafales de 15 sans pénalité et jusqu'à 20/sec. Donc au delà, c'est qu'il y a trop de requêtes générées je pense. Ptet pas la meilleure route d'utilisée

**Comment by romulusFR** [comment]
> n peut vite avoir beaucoup de requêtes qui arrivent en même temps, nottamment quand on répond à beaucoup de quizzes différents

Si ce sont des tests automatisés, effectivement ! C'est le cas ?

**Comment by MrBrownstone2000** [comment]
Ensuite le meilleur moyen d'être sur qu'il n'y ait pas de problème serait d'inclure les informations générales sur les quiz dans la réponse à  `GET users/answers`
Parce que là on est obligé de faire une requête par quiz où on a une réponse rien que pour afficher la liste. C'est surtout ça qui peut poser problème à mon avis

**Comment by MrBrownstone2000** [comment]
> Si ce sont des tests automatisés, effectivement ! C'est le cas ?

Non, mais quand en cherchant un bug ou une erreur, ou même pour tester manuellement, on peut vite oublier d'attendre entre les page reload. 
J'ai enlevé presque tous les fetch inutiles donc j'ai moins ce souci, mais ensuite, comme j'ai dit plus haut, ça dépend du nombre de quiz auquels on a répondu...

**Comment by Lifeismana** [comment]
+1 pour fournir des informations en plus à `GET users/answers` parce que si on veut afficher quoi que ce soit d'utile, on a forcement besoin de faire une requête à `/quizzes/{quiz_id}/`

**Comment by romulusFR** [comment]
Oui, OK, je vois. Qu'on ait pas juste le numéro dans https://lifap5.univ-lyon1.fr/api-docs/#/answers/getUserAnswers, pour que tu puisse construire la liste d'un coup.

**Comment by romulusFR** [comment]
Fait une update sur le serveur. Donc là, ya maintenant title et description

**Comment by MrBrownstone2000** [comment]
Serait-il possible de rajouter le owner_id pour que l'affichage soit raccord avec le reste des listes de quiz?

**Comment by MrBrownstone2000** [comment]
Merci pour l'update en tout cas
