### ISSUE TITLE
Suppression d'une proposition

### ISSUE THREAD

**Issue by LouisePietropaoli** [romulusFR/lifap5-backend-2019-2020#18]
Bonjour,

D'après la doc de l'API, il n'existe **pas de routes (dans la doc en tout cas) pour supprimer une proposition pour une question.**
Par ex : 

`{
  "quiz_id": 2507,
  "question_id": 0,
  "sentence": "Qui a encore pas inventé le lambda calcul ?",
  "propositions_number": 2,
  "correct_propositions_number": 2,
  "propositions": [
    {
      "content": "encore Alan Turing...",
      "proposition_id": 0
    },
    {
      "content": "Alonzo Church",
      "proposition_id": 1
    }
  ]
}`

 si j'ai cette question par ex
**et que je veux supprimer la proposition d'id 1**
J'ai essayé de faire un put avec ceci comme body :

`{
  "sentence": "Qui a encore pas inventé le lambda calcul ?",
  "propositions": [
    {
      "content": "encore Alan Turing...",
      "proposition_id": 0,
      "correct": true
    }
  ]
}`

 **mais la proposition d'id 1 reste quand même (car seule celle qui est modifiée est mise à jour)** 

Merci !

**Comment by MrBrownstone2000** [comment]
Je confirme, je viens de tester et effectivement, 

même en mettant un champ vide dans le "content" d'une proposition dans les données de la requête PUT, cette dernière n'est pas supprimée mais laissée tel quelle en étant vide.

`{
  "sentence": "Qui a encore pas inventé le lambda calcul ?",
  "propositions": [
    {
      "content": "encore Alan Turing",
      "proposition_id": 0,
      "correct": true
    },
    {
      "content": "",
      "proposition_id": 1,
      "correct":false
    }
  ]
}`

**Comment by romulusFR** [comment]
Effectivement, il n'y a pas de CRUD sur les propositions : tout doit se faire dans les questions. C'est pas top, mais ca me ferait changer un peu trop l'API. Donc je suis allé à la simplicité : j'ai modifié la consigne :), voir [la feature](https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/client/README.md)
