### ISSUE TITLE
Plusieurs réponses justes possibles à la création d'une question

### ISSUE THREAD

**Issue by MrBrownstone2000** [romulusFR/lifap5-backend-2019-2020#19]
Bonjour, 

Je viens de remarquer que quand on crée une nouvelle question pour un quizz, on peut donner plusieurs réponses justes, alors que dans l'API, on ne peut répondre qu'a une seule proposition par question...
il faudrait peut-être ajouter un check au niveau du serveur

Célian Louis-Itty p1807560

**Comment by romulusFR** [comment]
Disons qu'il faut répondre à une des justes... Je ne vais pas implémenter de réponses multiples ou de  verif de l'unicité de la proposition exacte (faudrait que je change le schéma pour bien faire) : je laisse le client s'en charger :)
