### ISSUE TITLE
Perte de l'information réponse correcte

### ISSUE THREAD

**Issue by LucieFournier** [romulusFR/lifap5-backend-2019-2020#20]
Bonjour,
J'ai l'impression que quand on crée une question, même en envoyant les données de propositions justes ou fausses, ces données se perdent : quand on cherche quizz/quizz_id/questions, on a toutes les informations sur la question et ses propositions, dont le nombre de propositions correctes... Mais il n'y a pas le booléen "correct" dans les propositions.

Par exemple, pour la question créée de base sur mon profil :
[{"quiz_id":3834,"question_id":0,"sentence":"Cette question a t'elle une réponse ?","propositions_number":2,"correct_propositions_number":1,"propositions":[{"content":"oui","proposition_id":0},{"content":"non","proposition_id":1}]}]

Merci d'avance !

**Comment by Webcretaire** [comment]
Cf #17 ➡️ l'info n'est pas perdue, mais dans la mesure où elle est "sensible", son accès est limité
