### ISSUE TITLE
Suppression des questions

### ISSUE THREAD

**Issue by marbrex** [romulusFR/lifap5-backend-2019-2020#23]
Selon la documentation il n'y a pas de route directe pour supprimer des questions d'un quiz. Ça serait bien de pouvoir supprimer juste une question au lieu de supprimer et après recréer tout le quiz.

Eldar Kasmamytov

**Comment by Lifeismana** [comment]
duplicate Cf #18

**Comment by marbrex** [comment]
> duplicate Cf #18

Non, parce que pour ajouter/modifier/supprimer les propositions tu dois passer par les questions, mais pour les questions on a des routes directes (on peut par exemple créer des questions directement).

**Comment by Webcretaire** [comment]
Non ce n'est pas un _duplicate_, cette issue parle des questions, pas des propositions.

Pour les questions la réponse est la suivante : la route [existe](https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/src/components/quizzes/questions/questionsRouter.js#L206), elle a juste échappé à la documentation. Elle fonctionne comme les autres suppression : un `DELETE` sur `/quizzes/{quizz_id}/questions/{question_id}`

**Comment by marbrex** [comment]
> Non ce n'est pas un _duplicate_, cette issue parle des questions, pas des propositions.
> 
> Pour les questions la réponse est la suivante : la route [existe](https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/src/components/quizzes/questions/questionsRouter.js#L206), elle a juste échappé à la documentation. Elle fonctionne comme les autres suppression : un `DELETE` sur `/quizzes/{quizz_id}/questions/{question_id}`

Oui. exactement

**Comment by marbrex** [comment]
Merci pour la réponse.

**Comment by marbrex** [comment]
> Non ce n'est pas un _duplicate_, cette issue parle des questions, pas des propositions.
> 
> Pour les questions la réponse est la suivante : la route [existe](https://github.com/romulusFR/lifap5-backend-2019-2020/blob/master/src/components/quizzes/questions/questionsRouter.js#L206), elle a juste échappé à la documentation. Elle fonctionne comme les autres suppressions : un `DELETE` sur `/quizzes/{quizz_id}/questions/{question_id}`

Si en utilisant ce méthode on supprime une question qui n'est pas la dernière dans le quiz, après on peut rencontrer des problèmes, comme par exemple la création d'une nouvelle question (si on utilise Array.length comme identifiant pour creer une question).

Par exemple, j'ai un quiz avec 3 questions, je supprime la deuxième question, et je me retrouve dans la situation où Array.length est 2. Si je veux ajouter une autre question après et j'utilise Array.length comme ID (je pense la plupart l'utilise), j'ai une erreur, car questions[2] existe déjà.

**Comment by marbrex** [comment]
Pour gérer ce problème on doit changer les identifiants de toutes les questions qui suivent? Ou au moment de la création chercher les "espaces vides" dans le tableau ?

**Comment by Webcretaire** [comment]
C'est effectivement à vous de gérer les ID des questions (contrairement à ceux des quizz qui sont auto-générés). Donc tu as tout à fait raison, utiliser `Array.length` pour attribuer un ID est dangereux, il faut à minima vérifier que l'ID n'existe pas déjà

Pour gérer ce problème il y a de nombreuses solutions, dans la mesure où c'est vous qui gérez les ID des questions c'est à vous de choisir (tu peux chercher le premier ID non-utilisé par exemple, ou partir d'`Array.length` et incrémenter tant qu'il y a conflit, etc.). En tout cas pour le backend ça n'a pas d'importance s'il y a des "trous" dans les ID des questions, il n'y a que les doublons qui sont interdits (pour un même quizz bien sûr)

**Comment by marbrex** [comment]
D'accord! Merci

**Comment by romulusFR** [comment]
C'est fait sur la v 1.0.6. Je la passe en prod là
